import datetime

EXPECTED_RESERVATION_DAYS = [
    [
        datetime.date(2019, 5, 13),
        {'user_reservated': False, 'session': 123, 'session_closed': True, 'hour': '10:00', 'reservations': [], 'date': 'El día 13-05-2019 a las 10:00', 'is_too_late': True, 'type': 'WOD'},
        {'user_reservated': False, 'session': 124, 'session_closed': True, 'hour': '11:00', 'reservations': [], 'date': 'El día 13-05-2019 a las 11:00', 'is_too_late': True, 'type': 'WOD'},
        {'user_reservated': False, 'session': 125, 'session_closed': True, 'hour': '12:00', 'reservations': [], 'date': 'El día 13-05-2019 a las 12:00', 'is_too_late': True, 'type': 'WOD'},
        {'user_reservated': False, 'session': 126, 'session_closed': True, 'hour': '13:00', 'reservations': [], 'date': 'El día 13-05-2019 a las 13:00', 'is_too_late': True, 'type': 'WOD'},
        {'user_reservated': False, 'session': 127, 'session_closed': True, 'hour': '17:00', 'reservations': [], 'date': 'El día 13-05-2019 a las 17:00', 'is_too_late': True, 'type': 'WOD'},
        {'user_reservated': False, 'session': 128, 'session_closed': True, 'hour': '18:00', 'reservations': [], 'date': 'El día 13-05-2019 a las 18:00', 'is_too_late': True, 'type': 'WOD'},
        {'user_reservated': False, 'session': 129, 'session_closed': True, 'hour': '19:00', 'reservations': [], 'date': 'El día 13-05-2019 a las 19:00', 'is_too_late': True, 'type': 'WOD'},
        {'user_reservated': False, 'session': 130, 'session_closed': True, 'hour': '20:00', 'reservations': [], 'date': 'El día 13-05-2019 a las 20:00', 'is_too_late': True, 'type': 'WOD'},
    ],
    [
        datetime.date(2019, 5, 14),
        {'user_reservated': False, 'session': 131, 'session_closed': False, 'hour': '10:00', 'reservations': [], 'date': 'El día 14-05-2019 a las 10:00', 'is_too_late': True, 'type': 'WOD'},
        {'user_reservated': False, 'session': 132, 'session_closed': False, 'hour': '11:00', 'reservations': [], 'date': 'El día 14-05-2019 a las 11:00', 'is_too_late': True, 'type': 'WOD'},
        {'user_reservated': False, 'session': 133, 'session_closed': False, 'hour': '12:00', 'reservations': [], 'date': 'El día 14-05-2019 a las 12:00', 'is_too_late': True, 'type': 'WOD'},
        {'user_reservated': False, 'session': 134, 'session_closed': False, 'hour': '13:00', 'reservations': [], 'date': 'El día 14-05-2019 a las 13:00', 'is_too_late': True, 'type': 'WOD'},
        {'user_reservated': False, 'session': 135, 'session_closed': False, 'hour': '17:00', 'reservations': [], 'date': 'El día 14-05-2019 a las 17:00', 'is_too_late': True, 'type': 'WOD'},
        {'user_reservated': False, 'session': 136, 'session_closed': False, 'hour': '18:00', 'reservations': [], 'date': 'El día 14-05-2019 a las 18:00', 'is_too_late': True, 'type': 'WOD'},
        {'user_reservated': False, 'session': 137, 'session_closed': False, 'hour': '19:00', 'reservations': [], 'date': 'El día 14-05-2019 a las 19:00', 'is_too_late': True, 'type': 'WOD'},
        {'user_reservated': False, 'session': 138, 'session_closed': False, 'hour': '20:00', 'reservations': [], 'date': 'El día 14-05-2019 a las 20:00', 'is_too_late': True, 'type': 'WOD'},
    ],
    [
        datetime.date(2019, 5, 15),
        {'user_reservated': False, 'session': 139, 'session_closed': False, 'hour': '10:00', 'reservations': [], 'date': 'El día 15-05-2019 a las 10:00', 'is_too_late': False, 'type': 'WOD'},
        {'user_reservated': False, 'session': 140, 'session_closed': False, 'hour': '11:00', 'reservations': [], 'date': 'El día 15-05-2019 a las 11:00', 'is_too_late': False, 'type': 'WOD'},
        {'user_reservated': False, 'session': 141, 'session_closed': False, 'hour': '12:00', 'reservations': [], 'date': 'El día 15-05-2019 a las 12:00', 'is_too_late': False, 'type': 'WOD'},
        {'user_reservated': False, 'session': 142, 'session_closed': False, 'hour': '13:00', 'reservations': [], 'date': 'El día 15-05-2019 a las 13:00', 'is_too_late': False, 'type': 'WOD'},
        {'user_reservated': False, 'session': 143, 'session_closed': False, 'hour': '17:00', 'reservations': [], 'date': 'El día 15-05-2019 a las 17:00', 'is_too_late': False, 'type': 'WOD'},
        {'user_reservated': False, 'session': 144, 'session_closed': False, 'hour': '18:00', 'reservations': [], 'date': 'El día 15-05-2019 a las 18:00', 'is_too_late': False, 'type': 'WOD'},
        {'user_reservated': False, 'session': 145, 'session_closed': False, 'hour': '19:00', 'reservations': [], 'date': 'El día 15-05-2019 a las 19:00', 'is_too_late': False, 'type': 'WOD'},
        {'user_reservated': False, 'session': 146, 'session_closed': False, 'hour': '20:00', 'reservations': [], 'date': 'El día 15-05-2019 a las 20:00', 'is_too_late': False, 'type': 'WOD'},
    ],
    [
        datetime.date(2019, 5, 16),
        {'user_reservated': False, 'session': 147, 'session_closed': False, 'hour': '10:00', 'reservations': [], 'date': 'El día 16-05-2019 a las 10:00', 'is_too_late': False, 'type': 'WOD'},
        {'user_reservated': False, 'session': 148, 'session_closed': False, 'hour': '11:00', 'reservations': [], 'date': 'El día 16-05-2019 a las 11:00', 'is_too_late': False, 'type': 'WOD'},
        {'user_reservated': False, 'session': 149, 'session_closed': False, 'hour': '12:00', 'reservations': [], 'date': 'El día 16-05-2019 a las 12:00', 'is_too_late': False, 'type': 'WOD'},
        {'user_reservated': False, 'session': 150, 'session_closed': False, 'hour': '13:00', 'reservations': [], 'date': 'El día 16-05-2019 a las 13:00', 'is_too_late': False, 'type': 'WOD'},
        {'user_reservated': False, 'session': 151, 'session_closed': False, 'hour': '17:00', 'reservations': [], 'date': 'El día 16-05-2019 a las 17:00', 'is_too_late': False, 'type': 'WOD'},
        {'user_reservated': False, 'session': 152, 'session_closed': False, 'hour': '18:00', 'reservations': [], 'date': 'El día 16-05-2019 a las 18:00', 'is_too_late': False, 'type': 'WOD'},
        {'user_reservated': False, 'session': 153, 'session_closed': False, 'hour': '19:00', 'reservations': [], 'date': 'El día 16-05-2019 a las 19:00', 'is_too_late': False, 'type': 'WOD'},
        {'user_reservated': False, 'session': 154, 'session_closed': False, 'hour': '20:00', 'reservations': [], 'date': 'El día 16-05-2019 a las 20:00', 'is_too_late': False, 'type': 'WOD'},
    ],
    [
        datetime.date(2019, 5, 17),
        {'user_reservated': False, 'session': 155, 'session_closed': False, 'hour': '10:00', 'reservations': [], 'date': 'El día 17-05-2019 a las 10:00', 'is_too_late': False, 'type': 'WOD'},
        {'user_reservated': False, 'session': 156, 'session_closed': False, 'hour': '11:00', 'reservations': [], 'date': 'El día 17-05-2019 a las 11:00', 'is_too_late': False, 'type': 'WOD'},
        {'user_reservated': False, 'session': 157, 'session_closed': False, 'hour': '12:00', 'reservations': [], 'date': 'El día 17-05-2019 a las 12:00', 'is_too_late': False, 'type': 'WOD'},
        {'user_reservated': False, 'session': 158, 'session_closed': False, 'hour': '13:00', 'reservations': [], 'date': 'El día 17-05-2019 a las 13:00', 'is_too_late': False, 'type': 'WOD'},
        {'user_reservated': False, 'session': 159, 'session_closed': False, 'hour': '17:00', 'reservations': [], 'date': 'El día 17-05-2019 a las 17:00', 'is_too_late': False, 'type': 'WOD'},
        {'user_reservated': False, 'session': 160, 'session_closed': False, 'hour': '18:00', 'reservations': [], 'date': 'El día 17-05-2019 a las 18:00', 'is_too_late': False, 'type': 'WOD'},
        {'user_reservated': False, 'session': 161, 'session_closed': False, 'hour': '19:00', 'reservations': [], 'date': 'El día 17-05-2019 a las 19:00', 'is_too_late': False, 'type': 'WOD'},
        {'user_reservated': False, 'session': 162, 'session_closed': False, 'hour': '20:00', 'reservations': [], 'date': 'El día 17-05-2019 a las 20:00', 'is_too_late': False, 'type': 'WOD'},
    ],
    [
        datetime.date(2019, 5, 18),
        {'user_reservated': False, 'session': None ,'session_closed': None, 'hour': '10:00', 'reservations': [], 'date': '', 'is_too_late': False, 'type': None},
        {'user_reservated': False, 'session': None ,'session_closed': None, 'hour': '11:00', 'reservations': [], 'date': '', 'is_too_late': False, 'type': None},
        {'user_reservated': False, 'session': None ,'session_closed': None, 'hour': '12:00', 'reservations': [], 'date': '', 'is_too_late': False, 'type': None},
        {'user_reservated': False, 'session': None ,'session_closed': None, 'hour': '13:00', 'reservations': [], 'date': '', 'is_too_late': False, 'type': None},
        {'user_reservated': False, 'session': None ,'session_closed': None, 'hour': '17:00', 'reservations': [], 'date': '', 'is_too_late': False, 'type': None},
        {'user_reservated': False, 'session': None ,'session_closed': None, 'hour': '18:00', 'reservations': [], 'date': '', 'is_too_late': False, 'type': None},
        {'user_reservated': False, 'session': None ,'session_closed': None, 'hour': '19:00', 'reservations': [], 'date': '', 'is_too_late': False, 'type': None},
        {'user_reservated': False, 'session': None ,'session_closed': None, 'hour': '20:00', 'reservations': [], 'date': '', 'is_too_late': False, 'type': None},
    ]
]