# Generated by Django 2.0.7 on 2018-08-01 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField(verbose_name='Hora de la sessión')),
            ],
            options={
                'verbose_name': 'Hora',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assisted', models.BooleanField(default=True, verbose_name='Asistencia')),
                ('cancelled', models.BooleanField(default=False, verbose_name='Cancelado')),
                ('paid', models.BooleanField(default=False, verbose_name='Pagado')),
            ],
            options={
                'verbose_name': 'Reserva',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=True, verbose_name='Día')),
                ('hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crossbox.Hour')),
            ],
            options={
                'verbose_name': 'Sesión',
                'verbose_name_plural': 'Sesiones',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crossbox.Session'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('date', 'hour')},
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('user', 'session')},
        ),
    ]
