# Generated by Django 3.0.8 on 2021-05-01 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='stripe_price_id',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='stripe_product_id',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='stripe_subscription_price_item_id',
        ),
    ]
