# Generated by Django 2.0.7 on 2018-08-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hour',
            name='hour',
            field=models.TimeField(unique=True, verbose_name='Hora de la sessión'),
        ),
    ]
