# Generated by Django 3.0.8 on 2020-08-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='last_payment_datetime',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='stipe_last_payment_timestamp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fecha último pago'),
        ),
    ]
