# Generated by Django 3.0.8 on 2020-07-30 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessiontemplate',
            unique_together={('day', 'hour', 'week_template')},
        ),
    ]
