# Generated by Django 3.0.8 on 2020-08-01 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crossbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tipo de sesión')),
                ('default', models.BooleanField(default=False, verbose_name='Predeterminado')),
            ],
            options={
                'verbose_name': 'Tipo de Sesión',
                'verbose_name_plural': 'Tipos de Sesión',
            },
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crossbox.SessionType'),
        ),
    ]
