# Generated by Django 3.0.8 on 2021-05-01 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossbox', '0002_auto_20210501_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='stipe_last_payment_timestamp',
            new_name='stripe_last_payment_timestamp',
        ),
    ]
