# Generated by Django 3.0.8 on 2020-08-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossbox', '0002_auto_20200817_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='stripe_billing_cycle_anchor',
            new_name='stripe_next_payment_timestamp',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='stipe_last_payment_timestamp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Timestamp último pago'),
        ),
    ]
