# Generated by Django 2.0.7 on 2018-08-12 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crossbox', '0002_auto_20180801_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Día de la semana')),
            ],
            options={
                'verbose_name': 'Día',
            },
        ),
        migrations.CreateModel(
            name='SessionTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crossbox.Day')),
                ('hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crossbox.Hour')),
            ],
            options={
                'verbose_name': 'Plantilla de Sesión',
                'verbose_name_plural': 'Plantilla de Sesión',
            },
        ),
        migrations.AlterUniqueTogether(
            name='sessiontemplate',
            unique_together={('day', 'hour')},
        ),
    ]
