# Generated by Django 3.0.8 on 2020-07-30 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossbox', '0002_auto_20200730_0815'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('date', 'hour', 'track')},
        ),
    ]
