# Generated by Django 3.0.8 on 2020-08-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossbox', '0002_subscriber_stripe_billing_cycle_anchor'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='stripe_subscription_price_item_id',
            field=models.CharField(max_length=30, null=True, verbose_name='ID Precio de Subscripción Stripe'),
        ),
    ]
