# Generated by Django 3.0.8 on 2020-08-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossbox', '0003_auto_20200817_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ID Subscripción Stripe'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='stripe_subscription_price_item_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ID Precio de Subscripción Stripe'),
        ),
    ]
