# Generated by Django 3.0.8 on 2020-08-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossbox', '0003_subscriber_stripe_subscription_price_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='last_payment_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha último pago'),
        ),
    ]
