# Generated by Django 2.0.7 on 2018-08-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossbox', '0003_auto_20180812_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessiontemplate',
            options={'verbose_name': 'Plantilla de Sesión', 'verbose_name_plural': 'Plantillas de Sesión'},
        ),
        migrations.AddField(
            model_name='day',
            name='weekday',
            field=models.IntegerField(unique=True, verbose_name='Número de dia de la semana (Lunes es 0)'),
            preserve_default=False,
        ),
    ]
