# Generated by Django 3.0.14 on 2022-01-15 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crossbox', '0004_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crossbox.Fee'),
        ),
    ]
