# Generated by Django 2.1.4 on 2018-12-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossbox', '0005_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='tickets',
            field=models.IntegerField(default=0),
        ),
    ]
