# Generated by Django 2.1.4 on 2019-01-05 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossbox', '0006_auto_20181231_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='cancelled',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='paid',
        ),
    ]
