# Generated by Django 3.1.14 on 2022-01-15 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crossbox', '0006_payment_wods'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crossbox.sessiontemplate'),
        ),
    ]
