# Generated by Django 3.1.14 on 2022-01-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossbox', '0007_session_session_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='session_template',
        ),
        migrations.AddField(
            model_name='session',
            name='morning',
            field=models.BooleanField(default=False, verbose_name='Sesión de mañana'),
        ),
        migrations.AddField(
            model_name='sessiontemplate',
            name='morning',
            field=models.BooleanField(default=False, verbose_name='Sesión de mañana'),
        ),
    ]
