# Generated by Django 2.1.4 on 2019-01-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossbox', '0007_auto_20190105_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='tickets',
            new_name='wods',
        ),
    ]
