# Generated by Django 3.1.14 on 2022-01-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossbox', '0008_auto_20220115_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='morning',
            field=models.BooleanField(default=False, verbose_name='Sesión de mañana'),
        ),
    ]
