# Generated by Django 2.1.5 on 2019-05-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossbox', '0008_auto_20190105_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='weekday',
            field=models.IntegerField(unique=True, verbose_name='Número de día de la semana (Lunes es 0)'),
        ),
        migrations.AlterField(
            model_name='hour',
            name='hour',
            field=models.TimeField(unique=True, verbose_name='Hora de la sesión'),
        ),
    ]
