# Generated by Django 3.1.14 on 2022-02-02 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crossbox', '0009_fee_morning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payed_amount',
            field=models.IntegerField(verbose_name='Precio pagado en céntimos'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crossbox.subscriber'),
        ),
    ]
