# Generated by Django 2.2.4 on 2019-08-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossbox', '0010_auto_20190820_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('wod', 'WOD'), ('open', 'OPEN'), ('stre', 'ESTIRAMIENTOS')], default='wod', max_length=4),
        ),
    ]
