# Generated by Django 3.1.14 on 2022-02-12 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crossbox', '0010_auto_20220202_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontemplate',
            name='session_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='crossbox.sessiontype'),
            preserve_default=False,
        ),
    ]
