# Generated by Django 3.1.14 on 2022-11-13 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossbox', '0011_sessiontemplate_session_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='morning',
            new_name='discount',
        ),
    ]
