# Generated by Django 3.1.14 on 2022-11-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossbox', '0011_sessiontemplate_session_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='morning',
        ),
        migrations.RemoveField(
            model_name='session',
            name='morning',
        ),
        migrations.RemoveField(
            model_name='sessiontemplate',
            name='morning',
        ),
        migrations.AddField(
            model_name='fee',
            name='discount',
            field=models.BooleanField(default=False, verbose_name='Horario descuento'),
        ),
        migrations.AddField(
            model_name='session',
            name='discount',
            field=models.BooleanField(default=False, verbose_name='Horario descuento'),
        ),
        migrations.AddField(
            model_name='sessiontemplate',
            name='discount',
            field=models.BooleanField(default=False, verbose_name='Horario descuento'),
        ),
    ]
