# Generated by Django 3.0.8 on 2020-07-27 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossbox', '0012_auto_20200727_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='refund',
        ),
    ]
