# Generated by Django 3.1.14 on 2022-11-13 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossbox', '0013_auto_20221113_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessiontemplate',
            old_name='morning',
            new_name='discount',
        ),
    ]
