# Generated by Django 3.0.8 on 2020-07-29 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crossbox', '0013_remove_reservation_refund'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum', models.IntegerField(verbose_name='Mínimo')),
                ('maximum', models.IntegerField(verbose_name='Máximo')),
                ('default', models.BooleanField(default=False, verbose_name='Predeterminado')),
            ],
            options={
                'verbose_name': 'Límite de Aforo',
                'verbose_name_plural': 'Límites de Aforo',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Pista')),
                ('default', models.BooleanField(default=False, verbose_name='Predeterminada')),
            ],
            options={
                'verbose_name': 'Pista',
                'verbose_name_plural': 'Pistas',
            },
        ),
        migrations.CreateModel(
            name='WeekTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Plantilla de semana')),
                ('default', models.BooleanField(default=False, verbose_name='Predeterminada')),
            ],
            options={
                'verbose_name': 'Plantilla de Semana',
                'verbose_name_plural': 'Plantillas de Semana',
            },
        ),
        migrations.AddField(
            model_name='session',
            name='appraisal_limit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='crossbox.AppraisalLimit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='track',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='crossbox.Track'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessiontemplate',
            name='week_template',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crossbox.WeekTemplate'),
            preserve_default=False,
        ),
    ]
